export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    c: "C",
    cpp: "C++",
    sql: "SQL",
    sqlite: "SQLite",
    postgresql: "PostgreSQL",
    mysql: "MySQL",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    streamlit: "Streamlit",
    jupyter: "Jupyter Notebook",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    tableau: "Tableau",
    xfce: "XFCE",
    react: "React",
    tensorflow: "TensorFlow",
    pytorch: "PyTorch",
    "scikit-learn": "Scikit-Learn",
    pandas: "Pandas",
    numpy: "NumPy",
    matplotlib: "Matplotlib",
    seaborn: "Seaborn",
    plotly: "Plotly",
    huggingface: "Hugging Face",
    nltk: "NLTK",
    prisma: "Prisma",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next.js",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
}